version: "2"
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.0
    restart: always
    network_mode: host
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - cluster.name=jgBay-cluster
      - bootstrap.memory_lock=true
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

# Must be mounted like this or else permission aren't correct
volumes:
  esdata:
    driver: local
